# @package _global_
_target_: src.model.deepspeech2.DeepSpeech2

# Model architecture parameters
n_tokens: 29         
n_feats: 80           
dim: 512              
n_channels: 48        
gru_layers: 5         
dropout: 0.3          