
_target_: src.trainer.trainer.Trainer

n_epochs: 100
save_period: 5
early_stop: 20
max_grad_norm: 1.0

device: "auto"
device_tensors: ["spectrogram", "text_encoded"]

log_step: 50
skip_oom: True

save_dir: "outputs"
monitor: "min val_cer"
seed: 42
